/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IBasicIssuanceModule } from "./IBasicIssuanceModule";

export class IBasicIssuanceModuleFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBasicIssuanceModule {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IBasicIssuanceModule;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256"
      }
    ],
    name: "getRequiredComponentUnitsForIssue",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]"
      },
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
