/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IModule } from "./IModule";

export class IModuleFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IModule {
    return new Contract(address, _abi, signerOrProvider) as IModule;
  }
}

const _abi = [
  {
    inputs: [],
    name: "removeModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  }
];
