/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IOracleInterface extends Interface {
  functions: {
    read: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export declare class IOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IOracle;
  attach(addressOrName: string): IOracle;
  deployed(): Promise<IOracle>;

  on(event: EventFilter | string, listener: Listener): IOracle;
  once(event: EventFilter | string, listener: Listener): IOracle;
  addListener(eventName: EventFilter | string, listener: Listener): IOracle;
  removeAllListeners(eventName: EventFilter | string): IOracle;
  removeListener(eventName: any, listener: Listener): IOracle;

  interface: IOracleInterface;

  functions: {
    read(): Promise<BigNumber>;
  };

  read(): Promise<BigNumber>;

  filters: {};

  estimate: {
    read(): Promise<BigNumber>;
  };
}
