/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IOracleAdapter } from "./IOracleAdapter";

export class IOracleAdapterFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleAdapter {
    return new Contract(address, _abi, signerOrProvider) as IOracleAdapter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_assetOne",
        type: "address"
      },
      {
        internalType: "address",
        name: "_assetTwo",
        type: "address"
      }
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
