/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPriceOracleInterface extends Interface {
  functions: {
    getPrice: TypedFunctionDescription<{
      encode([_assetOne, _assetTwo]: [string, string]): string;
    }>;

    masterQuoteAsset: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export declare class IPriceOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPriceOracle;
  attach(addressOrName: string): IPriceOracle;
  deployed(): Promise<IPriceOracle>;

  on(event: EventFilter | string, listener: Listener): IPriceOracle;
  once(event: EventFilter | string, listener: Listener): IPriceOracle;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IPriceOracle;
  removeAllListeners(eventName: EventFilter | string): IPriceOracle;
  removeListener(eventName: any, listener: Listener): IPriceOracle;

  interface: IPriceOracleInterface;

  functions: {
    getPrice(_assetOne: string, _assetTwo: string): Promise<BigNumber>;

    masterQuoteAsset(): Promise<string>;
  };

  getPrice(_assetOne: string, _assetTwo: string): Promise<BigNumber>;

  masterQuoteAsset(): Promise<string>;

  filters: {};

  estimate: {
    getPrice(_assetOne: string, _assetTwo: string): Promise<BigNumber>;

    masterQuoteAsset(): Promise<BigNumber>;
  };
}
