/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ISetValuer } from "./ISetValuer";

export class ISetValuerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISetValuer {
    return new Contract(address, _abi, signerOrProvider) as ISetValuer;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISetToken",
        name: "_setToken",
        type: "address"
      },
      {
        internalType: "address",
        name: "_quoteAsset",
        type: "address"
      }
    ],
    name: "calculateSetTokenValuation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
